name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          which brew
          brew install python@3.9 python@3.10 python@3.11
      - name: Fetch dependencies
        run: |
          /usr/local/bin/python3.9 --version
          /usr/local/bin/python3.9 -m pip install ivpm
          /usr/local/bin/python3.9 -m ivpm update
          /usr/local/bin/python3.9 -m pip install cython setuptools wheel build
      - name: Build wheel
        run: |
          ./packages/python/bin/python setup.py build_ext