name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          which brew
          brew install python@3.9 python@3.10 python@3.11
      - name: Fetch dependencies
        run: |
          python3 --version
          python3 -m pip install ivpm cython setuptools wheel build
          python3 -m ivpm update
      - name: Build wheel
          ./packages/python/bin/python -m build