name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-macos-arm64:
    strategy:
      matrix:
        pyversion: [3.9 3.10 3.11]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          which brew
          python="python@${{ matrix.pyversion }}"
          brew install $python
      - name: Fetch dependencies
        run: |
          python="/usr/local/bin/python${{ matrix.pyversion }}"
          $python -m pip install ivpm
          /usr/local/bin/python${{ matrix.pyversion }} -m ivpm update
          /usr/local/bin/python${{ matrix.pyversion }} -m pip install cython setuptools wheel build
      - name: Build wheel
        run: |
          ./packages/python/bin/python -m build