name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-macos-arm64:
    strategy:
      matrix:
        pyversion: ["3.9", "3.10", "3.11"]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          which brew
          python="python@${{ matrix.pyversion }}"
          echo "python=$python"
          brew install ${{ format('python@{0}', matrix.pyversion) }} ninja
      - name: Fetch dependencies
        run: |
          ${{ format('/usr/local/bin/python{0}', matrix.pyversion) }} -m pip install ivpm
          ${{ format('/usr/local/bin/python{0}', matrix.pyversion) }} -m ivpm update
          ./packages/python/bin/python -m pip install cython setuptools wheel build
      - name: Build wheel
        run: |
          ./packages/python/bin/python setup.py bdist_wheel