name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch dependencies
        run: |
          python3 --version
          python3 -m pip install ivpm
          python3 -m ivpm update
          ./packages/python/bin/python -m pip install cython setuptools wheel build
      - name: Build wheel
        run: |
          ./packages/python/bin/python setup.py bdist_wheel