name: CI
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ci-macos-arm64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch dependencies
        run: |
          arch
          python3 --version
          python3 -m pip install ivpm cython setuptools wheel
          python3 -p ivpm update
          ./packages/python/bin/python setup.py bdist_wheel